apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ausseabed-prod-cluster
  region: ap-southeast-2

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    instanceType: t2.small
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        albIngress: true
        cloudWatch: true
    
