apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: spt
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: www
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: www
    spec:
      containers:
        - image: 831535125571.dkr.ecr.ap-southeast-2.amazonaws.com/ausseabed-prod-sct-www:3d3c757a30b9e331b3e6f0060a319080fd62187b
          imagePullPolicy: Always
          name: www
          env:
          - name: NODE_ENV
            value: "production"
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: www
  name: www
  namespace: spt
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app.kubernetes.io/name: www
