apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www
  namespace: spt
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: www
    spec:
      containers:
        - image: ausseabed/spt-www:a6fc4ff
          imagePullPolicy: Always
          name: www
          env:
          - name: NODE_ENV
            value: "production"
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: spt
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    k8s-app: www
