apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: spt
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - image: 288871573946.dkr.ecr.ap-southeast-2.amazonaws.com/ausseabed-staging-sct-api:latest
          imagePullPolicy: Always
          name: api
          env:
          - name: AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: AUTH_CLIENT_ID
          - name: AUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: AUTH_CLIENT_SECRET
          - name: JWT_TOKEN_KEY_PRIVATE
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: JWT_TOKEN_KEY_PRIVATE
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: POSTGRES_PASSWORD
          - name: NODE_ENV
            value: "production"
          - name: RDS_MODE
            value: "true"
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: spt-secrets
                key: POSTGRES_HOSTNAME
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "postgres"
          - name: AUTH_HOST
            value: "https://ausseabed-nonprod.auth.ap-southeast-2.amazoncognito.com"
          - name: AWS_REGION
            value: "ap-southeast-2"
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
  namespace: spt
spec:
  ports:
   - port: 3000
     targetPort: 3000
  type: NodePort
  selector:
    app.kubernetes.io/name: api
